name: one

run-name: onerun

on:
  pull_request:
    branches:
      - main


# schedule:
#   - cron: '0 0 * * *'


jobs:
  job1:
    name: pull request
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "step1"